version : '3.8'

services :
    
    # Postgres Configuration
    postgres :
        
        image: postgres:16
        container_name: mailflow-postgres
        
        environment:
            
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            
        ports:
            - "5432:5432"
            
        volumes:
            - postgres_data:/var/lib/postgresql/data
            
        networks:
            - mailflow-networks
            
    # Ingestion Service
    ingestion-service:
        
        image: mailflow-ingestion:latest
        container_name: mailflow-ingestion 
        ports:
            - "8081 : 8081"
            
        environment:
        
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            
        depends_on:
            - postgres
            
        networks:
            - mailflow-networks
            
    # Classification Service
    classification-service:
    
        image: mailflow-classification:latest
        container_name: mailflow-classification
        
        ports:
            - "8082 : 8082"
        
        environment:
        
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            OLLAMA_API_URL: http://host.docker.internal:11434/api/generate
            
        depends-on:
            - postgres
            
        extra_hosts:
            - "host.docker.internal:host-gateway"
            
        networks:
            - mailflow-network
            
    # Routing Service
    routing-service:
        
        image: mailflow-routing:latest
        container_name: mailflow-routing
        
        ports:
            - "8083 : 8083"
        
        environment:

            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            
        depends-on:
            - postgres
            
        networks:
            - mailflow-network
        
        
    # Response Service
    response-service:
    
        image: mailflow-response:latest
        container_name: mailflow-response
        
        ports:
            - "8084 : 8084"
        
        environment:
        
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            OLLAMA_API_URL: http://host.docker.internal:11434/api/generate
            
        depends-on:
            - postgres
            
        extra_hosts:
            - "host.docker.internal:host-gateway"
            
        networks:
            - mailflow-network
            
    
    #Notification service
    notification-service:
    
        image: mailflow-notification:latest
        container_name: mailflow-notification
        
        ports:
            - "8085 : 8085"
        
        environment:

            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            
        depends-on:
            - postgres
            
        networks:
            - mailflow-network
            
            
    networks:
        mailflow-network:
            driver: bridge        
    
    volumes:
        postgres_data:
    
        
            
            
            
            
        

            
            
            
    
        
    
